install:
  - set QTDIR=C:\Qt\5.6\msvc2015
  - set PATH=%PATH%;%QTDIR%\bin

build_script:
  - qmake "DEFINES+=CI"
  - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86
  - nmake

before_deploy:
  - call "C:\Qt\5.6\msvc2015\bin\qtenv2.bat"
  - call "C:\Qt\5.6\msvc2015\bin\windeployqt" "C:\projects\apk-icon-editor\bin\win32\apk-icon-editor.exe" --compiler-runtime --no-translations --no-svg

artifacts:
  - path: bin\win32
    name: apk-icon-editor

deploy:
  - provider: GitHub
    tag: neutral
    release: Neutral Build
    description: Neutral Build
    draft: false
    prerelease: true
    force_update: true
    auth_token:
      secure: qPnC/xIWRP0KyP0UcXb7q3hsJNHt8bX80th1gVxV54GzRkdMBvRJVCfPZMB2Hm/S
    on:
      appveyor_scheduled_build: true
